services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ventas
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
